name: shipengine-php

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN}}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: shipengine-php
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: phpcs, phpstan, phpunit, php-cs-fixer
          extensions: xdebug
      - run: composer install
      - run: phpcs --standard=PSR2 src
      - run: phpstan analyse src --level 5
      - run: php-cs-fixer fix -vvv --config=.php_cs.dist
      - run: phpunit
      - run: ./vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v
  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - run: composer install
      - run: ./vendor/bin/phpdoc -d src/ -t docs/api
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
